name: "Re-trigger workflow on open Pull Requests"
description: "Re-triggers a configured workflow on open Pull Requests targeting a branch"
inputs:
  github_token:
    description: "The token to authenticate Octokit"
    required: true
runs:
  using: "node12"
  main: "index.js"
