on:
  issue_comment:
  pull_request:
    branches: "**"

jobs:
  one:
    if: contains(github.event.comment.body, 'Build:')
    runs-on: ubuntu-16.04
    steps:
      - name: Get buildInfo
        id: buildInfo
        run: |
          if [ ${{ github.event.pull_request }} ]; then
            x=${{ github.event.pull_request.user.login }}; 
            y=${{ github.head_ref }};
          else
            x=$(node -e "'${{ github.event.comment.body }}'.match(/Build: (.)+\/(.)+/ig)[0]"); 
            y=$(node -e "'${{ github.event.comment.body }}'.match(/Build: (.)+\/(.)+/ig)[1]"); 
          fi
          
          echo ::set-output name=user::$x
          echo ::set-output name=ref::$y
          
      - name: Print buildInfo
        id: pbuildInfo
        run: |
          echo -n ${{ github.steps.buildInfo.user }}
          echo -n ${{ github.steps.buildInfo.ref }}
          
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
