name: CI

on:
  pull_request:
    branches: "**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true


    steps:
      - uses: actions/checkout@v2
      
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Run echo
        id: echo
        run: |
          echo "Everything works."
        shell: bash
