name: CI

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: "**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true


    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      # This bash script will set an output version for this step. It can be used with steps.version.outputs.version
      - name: Run echo
        id: echo
        run: |
          echo "Everything works."
        shell: bash
