name: Retrigger CI on open PRs

on:
  push:

jobs:
  retrigger-ci-on-open-prs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/retrigger-workflow-on-open-prs
        with:
          github_token: ${{ secrets.RETRIGGER_CI_ON_OPEN_PRS_GITHUB_TOKEN }}
